# Use cuda for the vamb part of the pipeline. Uncomment to use cuda
# cuda: "True"

## databases
database: "/maps/projects/rasmussen/people/bxc755/taxvamb_benchmarks/database_to_be_moved/data.ace.uq.edu.au/public/gtdb/data/releases/latest"

metabuli_database: "/maps/projects/rasmussen/people/bxc755/taxvamb_benchmarks/metabuli_db/gtdb"
# metabuli_database: "/home/bxc755/rasmussen/people/bxc755/taxvamb_benchmarks/metabuli_database_220/gtdb+virus+human"

centrifuge_database_dir: "/maps/projects/rasmussen/people/bxc755/taxvamb_benchmarks/centri"
centrifuge_database_name: "abv"
gunc_database: "/maps/projects/rasmussen/people/bxc755/taxvamb_benchmarks/gunc_db/gunc_database/gunc_db_progenomes2.1.dmnd"

checkm2_database: "/maps/projects/rasmussen/people/bxc755/taxvamb_benchmarks/checkm2_database/CheckM2_database/uniref100.KO.1.dmnd"
kraken2_database: "/maps/projects/rasmussen/people/bxc755/taxvamb_benchmarks/airways/kraken_database_download"

# mmseqs databases
mmseqs_db_gtdb: "/maps/projects/rasmussen/people/bxc755/taxvamb_benchmarks/download_gtdb/gtdb_mmseqs"
mmseqs_db_trembl: "/maps/projects/rasmussen/people/bxc755/taxvamb_benchmarks/download_trembl/trembl_mmseqs"
mmseqs_db_kalmari: "/maps/projects/rasmussen/people/bxc755/taxvamb_benchmarks/download_kalmari/kalmari_mmseqs"

gunc_db: "/maps/projects/rasmussen/people/bxc755/taxvamb_benchmarks/gunc_db/gunc_database/gunc_db_progenomes2.1.dmnd"

# Use minimap - if False uses strobealign
use_minimap: True

## Default resources
# This is the default resources used by the different rules
# If no specific resources are defined for a rule, these will be used.
# If these exceed the resources available they will be scaled down to match the hardware available. 
# See https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#resources for reference
default_walltime: "20-00:00:00"
default_threads: 128
default_mem_gb: 500

## Specific rule resources
# Below is the specific resources defined for the various rules in the pipeline 
# If no specific resources are defined for a rule, the default will be used instead.
run_taxvamb_kraken:
  walltime: "20-00:00:00"
  mem_gb: 500
  threads: 64
  gpu: " --partition=gpuqueue --gres=gpu:1 "
run_taxvamb_premade:
  walltime: "20-00:00:00"
  mem_gb: 500
  threads: 64
  gpu: " --partition=gpuqueue --gres=gpu:1 "

run_taxvamb_gtdb:
  walltime: "20-00:00:00"
  mem_gb: 500
  threads: 64
  gpu: " --partition=gpuqueue --gres=gpu:1 "

run_taxvamb_centrifuge:
  walltime: "20-00:00:00"
  mem_gb: 500
  threads: 64
  gpu: " --partition=gpuqueue --gres=gpu:1 "

run_taxvamb_gtdb_no_predictor:
  walltime: "20-00:00:00"
  mem_gb: 500
  threads: 64
  gpu: " --partition=gpuqueue --gres=gpu:1 "

run_taxvamb_kalmari:
  walltime: "20-00:00:00"
  mem_gb: 500
  threads: 64
  gpu: " --partition=gpuqueue --gres=gpu:1 "

run_taxvamb_metabuli:
  walltime: "20-00:00:00"
  mem_gb: 500
  threads: 64
  gpu: " --partition=gpuqueue --gres=gpu:1 "

run_taxvamb_no_predictor_kraken:
  walltime: "20-00:00:00"
  mem_gb: 500
  threads: 64
  gpu: " --partition=gpuqueue --gres=gpu:1 "
run_taxvamb_no_predictor_centrifuge:
  walltime: "20-00:00:00"
  mem_gb: 500
  threads: 64
  gpu: " --partition=gpuqueue --gres=gpu:1 "

run_taxvamb_no_predictor_metabuli:
  walltime: "20-00:00:00"
  mem_gb: 500
  threads: 64
  gpu: " --partition=gpuqueue --gres=gpu:1 "

run_taxvamb_trembl:
  walltime: "20-00:00:00"
  mem_gb: 500
  threads: 64
  gpu: " --partition=gpuqueue --gres=gpu:1 "

run_vamb:
  walltime: "20-00:00:00"
  mem_gb: 500
  threads: 64
  gpu: " --partition=gpuqueue --gres=gpu:1 "


format_bins_class:
  walltime: "162:00:00"
  mem_gb: 20
  threads: 4
centrifuge:
  walltime: "162:00:00"
  mem_gb: 1500
  threads: 127
metabuli:
  walltime: "162:00:00"
  mem_gb: 1500
  threads: 127
kraken2:
  walltime: "162:00:00"
  mem_gb: 1500
  threads: 127
format_bins_taxvamb_gtdb:
  walltime: "162:00:00"
  mem_gb: 10
  threads: 2
format_bins_default_vamb:
  walltime: "162:00:00"
  mem_gb: 10
  threads: 2
format_bins_taxvamb_kalmari:
  walltime: "162:00:00"
  mem_gb: 10
  threads: 2
format_bins_taxvamb_trembl:
  walltime: "162:00:00"
  mem_gb: 10
  threads: 2
# gunc:
#   walltime: "162:00:00"
#   mem_gb: 100
#   threads: 80

comebin:
  walltime: "288:00:00"
semibin:
  walltime: "288:00:00"

centrifuge_db:
  walltime: "162:00:00"
  mem_gb: 1000
  threads: 60
kraken_db:
  walltime: "162:00:00"
  mem_gb: 200
  threads: 60
# mmseqs2_gtdb:
#   walltime: "162:00:00"
#   mem_gb: 1300
#   threads: 60
#
# mmseqs2_trembl:
#   walltime: "162:00:00"
#   mem_gb: 1300
#   threads: 60

rename_contigs:
  threads: 1
  default_mem_gb: 5

cat_contigs:
  threads: 1
  default_mem_gb: 5

get_contig_names:
  threads: 1
  default_mem_gb: 5

samtools_sort:
  threads: 4
  default_mem_gb: 20

spades:
  threads: 10
  mem_gb: 200

Strobealign_bam_default:
  threads: 10
  mem_gb: 245

sort:
  threads: 8
  mem_gb: 120

