# Use cuda for the vamb part of the pipeline. Uncomment to use cuda
# cuda: "True"

# Use minimap - if False uses strobealign
use_minimap: True

## Default resources
# This is the default resources used by the different rules
# If no specific resources are defined for a rule, these will be used.
# If these exceed the resources available they will be scaled down to match the hardware available. 
# See https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#resources for reference
default_walltime: "48:00:00"
default_threads: 16
default_mem_gb: 50

## Specific rule resources
# Below is the specific resources defined for the various rules in the pipeline 
# If no specific resources are defined for a rule, the default will be used instead.
rename_contigs:
  threads: 1
  default_mem_gb: 5

cat_contigs:
  threads: 1
  default_mem_gb: 5

get_contig_names:
  threads: 1
  default_mem_gb: 5

samtools_sort:
  threads: 4
  default_mem_gb: 20

spades:
  threads: 10
  mem_gb: 200

Strobealign_bam_default:
  threads: 10
  mem_gb: 245

sort:
  threads: 8
  mem_gb: 120

